### ISSUE TITLE
Mac need a few tweaks to CMake to work out of the box

### ISSUE THREAD

**Issue by ajc158** [BRAHMS-SystemML/brahms#12] opened 2016-02-25 16:23 UTC
brahms-execute should be moved to the same dir as brahms, and brahms should be made executable

**Comment by sebjameswml** [comment] 2016-02-25 16:26
They should already go in the same directory; in framework/execute/CMakeLists.txt I have:
```
# This means install the brahms-execute target into BIN_INSTALL_PATH (making it executable)
install(TARGETS brahms-execute DESTINATION ${BIN_INSTALL_PATH})
# This is similar, but uses PROGRAMS as it's a script - should also be executable and end up in the same location.
install(PROGRAMS brahms DESTINATION ${BIN_INSTALL_PATH})
```
So I'm puzzled that you find they don't. I'll fire up the Mac at home at some point...

**Comment by ajc158** [comment] 2016-02-25 16:29
Hmm... they have the following structure
`.../bin/
  brahms-execute
  /brahms/
    brahms
    <other brahms libs>`

**Comment by sebjameswml** [comment] 2016-05-17 14:46
Hi Alex, is this still an issue?

**Comment by sebjameswml** [comment] 2016-05-18 13:48
Yes, it is - I've just observed it on Alex Blenkinsop's installation.

**Comment by ajc158** [comment] 2016-05-18 13:52
I thought I created a pull request as you own the rep

**Comment by sebjameswml** [comment] 2016-05-18 13:54
I merged your pull request which was quite old. This issue isn't yet fixed, but I know what the problem is.

**Comment by sebjameswml** [comment] 2016-05-18 15:14
The problem with the brahms script appearing in a subdirecory on a STANDALONE build should be fixed with d063542

**Comment by sebjameswml** [comment] 2019-03-21 17:16
I reckon this issue is sorted.

**Closed by sebjameswml** 2019-03-21 17:16 UTC
